### PR TITLE
instructor updated for android

### PR DESCRIPTION
**Pull request by aditya81070**

### CODE REVIEW

**Comment by maddhruv** [comment]
Please check the discussion and also update the instructors

**Comment by maddhruv** [comment]
> Lecture 2 - Amrit Srivastava - Wed Mar 14
Lecture 3 - Dhruv Jain - Thus Mar 15
Lecture 4 - Dhruv Jain - Fri Mar 16
Lecture 5 - Dhruv Jain - Sat Mar 17

Check instructors name, same as for android

**Comment by aditya81070** [comment]
I already updated instructors for android.

**Comment by maddhruv** [comment]
so as android instructors

**Comment by aditya81070** [comment]
Android instructors have already updated according to the discussion at @CodeDocsJECRC/instructors

**Pull request closed without merging**
